language: go
go:
- 1.x
install:
- curl --verbose
       --form accept_license=1
       --form form_id=intel_licensed_dls_step_1
       --output /dev/null
       --cookie-jar jar.txt
       --location
       https://software.intel.com/protected-download/267266/157552
- curl -verbose
       --cookie jar.txt
       --output iaca.zip
       https://software.intel.com/system/files/managed/c8/65/iaca-version-v3.0-lin64.zip
- unzip iaca.zip
- export IACA_PATH=${TRAVIS_BUILD_DIR}/iaca-lin64
script:
- make -C example iaca.out
- cat example/iaca.out
